### ISSUE TITLE
relay firmware modification

### ISSUE THREAD

**Issue by VojislavM** [LoRaWanRelay/LoRaWanRelay#1]
Hi, 
I am currently trying to build and test your relay project. I am having issues with some parts and would really benefit from your answers. First I will explain my setup.
 
### Setup
1. I have Gateway connected to the TTN and working.
2. I have two boards B-L072Z-LRWAN1, one for the relay node and one for the regular node
3. Cloned main branch of your repo

### Installation
Following your instruction form [readme](https://github.com/LoRaWanRelay/LoRaWanRelay/blob/master/README.md) I have chaned the code in the [MainRelay.cpp](https://github.com/LoRaWanRelay/LoRaWanRelay/blob/master/UserCode/MainRelay.cpp) and put information about mine applcation and the device:
* line 47: `uint8_t LoRaMacAppKeyInit[]       = { 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0xBB};`
* line 48: `uint8_t AppEuiInit[]              = { 0x70, 0xb3, 0xd5, 0x7e, 0xd0, 0x00, 0xff, 0x50 };`
* line 49: `uint8_t DevEuiInit2[]             = { 0x38, 0x35, 0x31, 0x31, 0x18, 0x47, 0x37, 0x51 };`
* line 55: `uint8_t DevEuiInit[]       = { 0x38, 0x35, 0x31, 0x31, 0x18, 0x47, 0x37, 0x57 };` this one is the same as in the line 49, I chaned it because I noticed that `DevEuiInit2[]` is not used in the structure LoraWanKeys 

After compiling this code I get data in my gateway and application dashboard. The data looks like this:
![Inkedlora-relay-sending messages test1_LI](https://user-images.githubusercontent.com/8199477/56128342-a37eeb00-5f7f-11e9-896b-beb222d9bfe2.jpg)

As you see not every message has a same length. Is this ok?

**Comment by nestorayuso** [comment]
https://www.youtube.com/watch?v=cX9OtTBqHyM

**Comment by VojislavM** [comment]
@nestorayuso Sorry I do not speak French, but I have managed to get everything going. It is working but firmware needs more polishing. In the next days I will probably publish blog post of setting everything up on the [Irnas blog](https://www.irnas.eu/blog/)
